
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - builders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - builders/finalizers
  verbs:
  - update
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - builders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseers/finalizers
  verbs:
  - update
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - overseers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - servings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - servings/finalizers
  verbs:
  - update
- apiGroups:
  - quanxiang.cloud.io
  resources:
  - servings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipwright.io
  resources:
  - builders
  - buildruns
  - buildstrategies
  - clusterbuildstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
